/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ujian;

/**
 *
 * @author michael
 */
import Dictionary.Dictionary;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import com.jtattoo.plaf.fast.FastLookAndFeel;
import com.jtattoo.plaf.mcwin.McWinLookAndFeel;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.BufferedReader;
import java.io.InputStreamReader;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
import javax.swing.Timer;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;
import stemmerindo.Stemmer;
public class soal extends javax.swing.JFrame {
    int number= 1;
    int limit = 0;
    int id ;
    int id_soal;
    String token;
    String mapel;
    String waktu;
    
    static final String JDBC_DRIVER = "com.mysql.jdbc.Driver";
    static final String USER = "root";
    static final String PASS = "";
    static final String DB_URL = "jdbc:mysql://localhost/pbo";
    static Connection conn;
    static Statement stmt;
    static ResultSet rs;
    static ResultSet rs1;
    
    static InputStreamReader inputStreamReader = new InputStreamReader(System.in);
    static BufferedReader input = new BufferedReader(inputStreamReader);
    Connection con;
     Connection connn;
    Statement stat;
    String sql;
    int detik,menit;
    String nold,nolm;
    String npm1,nama1;
    int menit12;

    /**
     * Creates new form soal
     */
    public soal(String nama,String npm) {
        initComponents();
        jMenu2.setText(nama);
        idUser.setText(npm);
        npm1=npm;
        nama1=nama;
        
        limit = count_soal();
        soal(number,limit);
        id = Login.id_user;
        BTSubmit.setVisible(false);
        
//        idUser.setText(Integer.toString(id));
//     
        
       
        
    }

 private static void jawabanmahasiswa() {
        try {
            conn = DriverManager.getConnection(DB_URL, USER, PASS);
            stmt = conn.createStatement();
            
            String sql1= "SELECT * FROM jawaban";
            
            rs = stmt.executeQuery(sql1);
            List<String> jawaban_mhs = new ArrayList<>();
            while (rs.next()) {
                String jmahasiswa = rs.getString("jawaban");
                jawaban_mhs.add(jmahasiswa);
            }
            
//        String jawabanmahasiswa = ;
//        String sentence1 =jawabanmahasiswa;
//contoh penggunaannya        
//        List dictionary = new Dictionary().read().getDictionaryData();
List dictionary = new Dictionary().read("src/dictionary/dictionaries.properties").getDictionaryData(); //use specific path
Stemmer stemmer = new Stemmer(dictionary);
InputStreamReader isr = new InputStreamReader(System.in);

// membuat objek bufferreader
BufferedReader br = new BufferedReader(isr);

String sentence1 = "";                
for(int i=0;i<jawaban_mhs.size();i++){
    sentence1 = jawaban_mhs.get(i);
    String sentence2 = sentence1.toLowerCase();
    
    for (String word : sentence2.split(" ")) {
        String jawaban = sentence2;
        // println("\t" + word + " = " + stemmer.getRootWord(word));
        // query simpan
        String sql = "INSERT INTO stemming (kalimat,kataDasar, hasilStem) VALUE('%s','%s', '%s')";
        sql = String.format(sql,jawaban, word, stemmer.getRootWord(word,word));
        stmt.execute(sql);
    }
}




//        println(sentence2);
//        String jawaban = "";
     
//        for (String word : sentence2.split(" ")) {
//            String jawaban = sentence2;
//            println("\t" + word + " = " + stemmer.getRootWord(word));
//            // query simpan
//            String sql = "INSERT INTO stemming (kalimat,kataDasar, hasilStem) VALUE('%s','%s', '%s')";
//            sql = String.format(sql,jawaban, word, stemmer.getRootWord(word));
//            stmt.execute(sql);
//        }


stmt.close();
conn.close();
        } catch (SQLException ex) {
            Logger.getLogger(soal.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Exception ex) {
            Logger.getLogger(soal.class.getName()).log(Level.SEVERE, null, ex);
        }
       
        
        }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        jLabel17 = new javax.swing.JLabel();
        TAJawabanM = new javax.swing.JScrollPane();
        TAjawabanMahasiswa = new javax.swing.JTextArea();
        LabelSoal = new javax.swing.JLabel();
        BTSubmit = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        idUser = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        LabelToken = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        mulaiujian = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N

        TAjawabanMahasiswa.setColumns(20);
        TAjawabanMahasiswa.setRows(5);
        TAJawabanM.setViewportView(TAjawabanMahasiswa);

        LabelSoal.setText("jLabel1");

        BTSubmit.setText("submit");
        BTSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTSubmitActionPerformed(evt);
            }
        });

        jLabel1.setText("Soal");

        idUser.setText("idUser");

        jLabel2.setText("Token:");

        LabelToken.setText("jLabel3");

        jLabel3.setText("Durasi:");

        jLabel4.setText("jLabel4");

        jLabel5.setText("MataKuliah:");

        jLabel6.setText("jLabel6");

        jLabel7.setText("jLabel7");

        mulaiujian.setText("Mulai Ujian");
        mulaiujian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mulaiujianActionPerformed(evt);
            }
        });

        jMenu1.setText("hai,");
        jMenuBar1.add(jMenu1);
        jMenuBar1.add(jMenu2);

        jMenu3.setText("Logout");
        jMenu3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu3MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(TAJawabanM, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 627, Short.MAX_VALUE)
                                .addComponent(LabelSoal, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(LabelToken)
                                .addGap(76, 76, 76)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(41, 41, 41)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel7)
                                .addGap(66, 66, 66)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(mulaiujian)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(idUser)
                                        .addGap(259, 259, 259)
                                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(303, 303, 303)
                        .addComponent(BTSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3))
                    .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(idUser)
                        .addComponent(jLabel2)
                        .addComponent(LabelToken)
                        .addComponent(jLabel5)
                        .addComponent(jLabel7)))
                .addGap(18, 18, 18)
                .addComponent(mulaiujian)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(LabelSoal, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(TAJawabanM, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BTSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BTSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTSubmitActionPerformed
        // TODO add your handling code here:
      
        try {
            String jawaban = getTAJawabanM().getText();
            
            if (jawaban.isEmpty()){
                JOptionPane.showMessageDialog(TAJawabanM, "Can't empty.", "Warning",
                JOptionPane.WARNING_MESSAGE);
            }else{
                insertJawaban(jawaban);
               
                
                rs.next();
                
                id_soal = rs.getInt("id_soal");
                String soal = rs.getString("soal");
                LabelSoal.setText(id_soal+". "+soal);
                
                TAjawabanMahasiswa.setText("");
              
            }
           
             
                   
            
        } catch (SQLException ex) {
            jawabanmahasiswa();
            JOptionPane.showMessageDialog(TAJawabanM, "End of questions.", "Done",
            JOptionPane.CLOSED_OPTION);
        }
        
    }//GEN-LAST:event_BTSubmitActionPerformed

    private void mulaiujianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mulaiujianActionPerformed
        
            
           
                mulaiujian.setVisible(false);
                BTSubmit.setVisible(true);
                jLabel17.setVisible(true);
                detik=0;
                menit=menit12;
                countdown();
           
    }//GEN-LAST:event_mulaiujianActionPerformed

    private void jMenu3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu3MouseClicked
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jMenu3MouseClicked
     public JTextArea getTAJawabanM() {
        return TAjawabanMahasiswa ;
        }
 

    
     private int count_soal(){
        try {
            String host = "jdbc:mysql://localhost/pbo";
            String uName = "root";
            String uPass ="";
            conn = DriverManager.getConnection(host, uName, uPass);

            stmt = conn.createStatement();
            String sql = "SELECT COUNT(*) as count_soal FROM soal";
            rs=stmt.executeQuery(sql);
            rs.next();
            int id_col = rs.getInt("count_soal");
            
            
            
            return id_col;
            
        }catch ( SQLException err ) {
            System.out.println(err.getMessage());
            return 0;

        }   
    }
    public void soal(int start, int limit){
   
        try {
            String host = "jdbc:mysql://localhost/pbo";
            String uName = "root";
            String uPass ="";
            Connection con = DriverManager.getConnection(host, uName, uPass);

            Statement stat = con.createStatement();
            String sql1 = "SELECT * FROM setting";
             rs=stmt.executeQuery(sql1);


            rs.next();
            String mapel = rs.getString("mapel");
            String token = rs.getString("token");
            String waktu = rs.getString("waktu_mengerjakan");
            LabelToken.setText(token);
            jLabel4.setText(waktu);
            jLabel7.setText(mapel);
            menit12=Integer.parseInt(waktu);
    
            
            
            Statement stmt = con.createStatement();
            String sql = "SELECT * FROM soal";
             rs=stmt.executeQuery(sql);


            rs.next();
            id_soal = rs.getInt("id_soal");
            String soal = rs.getString("soal");
            LabelSoal.setText(id_soal+". "+soal);    
            
            
        }catch ( SQLException err ) {
            JOptionPane.showMessageDialog(TAJawabanM, "End of questions.", "Done",
            JOptionPane.CLOSED_OPTION);
        }   
    }
    
    public void insertJawaban(String jawaban){
        System.out.println("Masuk");
        // TODO add your handling code here:
        try {
                
            String sql = "INSERT INTO jawaban (jawaban, id_soal, nim) VALUES(?,?,?)";
            PreparedStatement pstmt = conn.prepareStatement(sql);
            pstmt.setString(1, jawaban);
            pstmt.setInt(2, id_soal);
            pstmt.setInt(3, id);
            pstmt.execute();
       
        } catch ( SQLException e) {
            System.out.println("error");
        }
        
    }private void tampil_setting(){
       
    }
 public final void countdown(){
        ActionListener taskperformer=new ActionListener() {
            
            public void actionPerformed(ActionEvent evt) {
                if (detik==0) {
                    menit=menit-1;
                }
                if(detik==0&&menit==-1){
                    detik=-1;
                    mulaiujian.doClick();
                }
                if (detik==0&&menit>=0) {
                    detik=60;
                }
                if (detik<=60&&detik>=0) {
                    detik=detik-1;
                }
                if (detik<=9) {
                    nold="0";
                }
                if (menit<=9) {
                    nolm="0";
                }
                if (detik>=0&&menit>=0) {
                    jLabel17.setText(menit+":"+detik);
                }
                if (detik>=0&&menit<0) {
                    jLabel17.setText("00:"+detik);
                }
            }
        };
        new Timer(1000,taskperformer).start();
    } 

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTSubmit;
    private javax.swing.JLabel LabelSoal;
    private javax.swing.JLabel LabelToken;
    private javax.swing.JScrollPane TAJawabanM;
    private javax.swing.JTextArea TAjawabanMahasiswa;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.JLabel idUser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JButton mulaiujian;
    // End of variables declaration//GEN-END:variables
}
